### ISSUE TITLE
Unable to train the model, there is an issue with the dataset

### ISSUE THREAD

**Issue by breakTBB** [h4iku/T5APR#1]
After running "python train_model.py," I encountered the following issue. When I directly access this [URL](https://huggingface.co/datasets/h4iku/coconut_java2006_preprocessed/resolve/76a94c2ccfd933177a62d8d5a5eea4ce4b84af34/README.md), it returns "Entry not found.
```
#python train_model.py 
CUDA available: True
CUDA version: 11.8
Traceback (most recent call last):
  File "train_model.py", line 31, in <module>
    raw_datasets = {
  File "train_model.py", line 32, in <dictcomp>
    prefix: load_dataset(data, split="train") for prefix, data in dataset_names.items()
  File "/root/miniconda3/lib/python3.8/site-packages/datasets/load.py", line 2129, in load_dataset
    builder_instance = load_dataset_builder(
  File "/root/miniconda3/lib/python3.8/site-packages/datasets/load.py", line 1815, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/root/miniconda3/lib/python3.8/site-packages/datasets/load.py", line 1512, in dataset_module_factory
    raise e1 from None
  File "/root/miniconda3/lib/python3.8/site-packages/datasets/load.py", line 1489, in dataset_module_factory
    return HubDatasetModuleFactoryWithoutScript(
  File "/root/miniconda3/lib/python3.8/site-packages/datasets/load.py", line 1031, in get_module
    dataset_readme_path = cached_path(
  File "/root/miniconda3/lib/python3.8/site-packages/datasets/utils/file_utils.py", line 182, in cached_path
    output_path = get_from_cache(
  File "/root/miniconda3/lib/python3.8/site-packages/datasets/utils/file_utils.py", line 601, in get_from_cache
    raise ConnectionError(f"Couldn't reach {url} (error {response.status_code})")
ConnectionError: Couldn't reach https://huggingface.co/datasets/h4iku/coconut_java2006_preprocessed/resolve/76a94c2ccfd933177a62d8d5a5eea4ce4b84af34/README.md (error 503)
```

**Comment by breakTBB** [comment]
sorry for the disturbance, it's just due to network issues.
